ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.4.210.161.192.nip.io
  path: /
  pathType: Prefix

service:
  type: ClusterIP

# Конфігурація Elasticsearch datasource
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: BeStrong-Logs
      type: elasticsearch
      access: proxy
      url: http://elasticsearch-service.default.svc.cluster.local:9200
      database: "fluentd-bestrong-*"
      isDefault: true
      editable: true
      jsonData:
        interval: Daily
        timeField: "@timestamp"
        esVersion: "7.17.0"
        logMessageField: "message"
        logLevelField: "level"
        includeFrozen: false
        maxConcurrentShardRequests: 5

# Налаштування для логів
env:
  GF_EXPLORE_ENABLED: "true"
  GF_LOGGING_LEVEL: "info"
  GF_FEATURE_TOGGLES_ENABLE: "logs"

persistence:
  enabled: true
  size: 2Gi

# Плагіни для роботи з логами
plugins:
  - grafana-piechart-panel

# Додаткові налаштування
adminPassword: "admin123"

# Конфігурація для кращої роботи з Elasticsearch
grafana.ini:
  explore:
    enabled: true
  log:
    level: info