ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.128.251.178.137.nip.io
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.128.251.178.137.nip.io
service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Elasticsearch
      type: elasticsearch
      url: http://elasticsearch-master:9200
      database: "bestrong-api-*"
      jsonData:
        timeField: "@timestamp"
        esVersion: 7
        logMessageField: log
        logLevelField: level

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'bestrong'
      orgId: 1
      folder: 'BeStrong'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/bestrong

dashboards:
  bestrong:
    bestrong-api-logs:
      json: |
        {
          "annotations": {
            "list": [
              {
                "builtIn": 1,
                "datasource": "-- Grafana --",
                "enable": true,
                "hide": true,
                "iconColor": "rgba(0, 211, 255, 1)",
                "name": "Annotations & Alerts",
                "type": "dashboard"
              }
            ]
          },
          "editable": true,
          "gnetId": null,
          "graphTooltip": 0,
          "id": 1,
          "links": [],
          "panels": [
            {
              "aliasColors": {},
              "bars": false,
              "dashLength": 10,
              "dashes": false,
              "datasource": "Elasticsearch",
              "fieldConfig": {
                "defaults": {
                  "custom": {}
                },
                "overrides": []
              },
              "fill": 1,
              "fillGradient": 0,
              "gridPos": {
                "h": 9,
                "w": 12,
                "x": 0,
                "y": 0
              },
              "hiddenSeries": false,
              "id": 2,
              "legend": {
                "avg": false,
                "current": false,
                "max": false,
                "min": false,
                "show": true,
                "total": false,
                "values": false
              },
              "lines": true,
              "linewidth": 1,
              "nullPointMode": "null",
              "options": {
                "dataLinks": []
              },
              "percentage": false,
              "pointradius": 2,
              "points": false,
              "renderer": "flot",
              "seriesOverrides": [],
              "spaceLength": 10,
              "stack": false,
              "steppedLine": false,
              "targets": [
                {
                  "bucketAggs": [
                    {
                      "field": "@timestamp",
                      "id": "2",
                      "settings": {
                        "interval": "auto",
                        "min_doc_count": 0,
                        "trimEdges": 0
                      },
                      "type": "date_histogram"
                    }
                  ],
                  "metrics": [
                    {
                      "field": "select field",
                      "id": "1",
                      "type": "count"
                    }
                  ],
                  "query": "",
                  "refId": "A",
                  "timeField": "@timestamp"
                }
              ],
              "thresholds": [],
              "timeRegions": [],
              "title": "API Request Count",
              "tooltip": {
                "shared": true,
                "sort": 0,
                "value_type": "individual"
              },
              "type": "graph",
              "xaxis": {
                "buckets": null,
                "mode": "time",
                "name": null,
                "show": true,
                "values": []
              },
              "yaxes": [
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                },
                {
                  "format": "short",
                  "label": null,
                  "logBase": 1,
                  "max": null,
                  "min": null,
                  "show": true
                }
              ],
              "yaxis": {
                "align": false,
                "alignLevel": null
              }
            },
            {
              "datasource": "Elasticsearch",
              "fieldConfig": {
                "defaults": {
                  "custom": {
                    "align": null
                  },
                  "mappings": [],
                  "thresholds": {
                    "mode": "absolute",
                    "steps": [
                      {
                        "color": "green",
                        "value": null
                      }
                    ]
                  }
                },
                "overrides": []
              },
              "gridPos": {
                "h": 8,
                "w": 24,
                "x": 0,
                "y": 9
              },
              "id": 4,
              "options": {
                "showHeader": true
              },
              "pluginVersion": "7.0.3",
              "targets": [
                {
                  "bucketAggs": [],
                  "metrics": [
                    {
                      "field": "log",
                      "id": "1",
                      "settings": {},
                      "type": "raw_document"
                    }
                  ],
                  "query": "",
                  "refId": "A",
                  "timeField": "@timestamp"
                }
              ],
              "timeFrom": null,
              "timeShift": null,
              "title": "Logs",
              "type": "table"
            }
          ],
          "refresh": "5s",
          "schemaVersion": 25,
          "style": "dark",
          "tags": [],
          "templating": {
            "list": []
          },
          "time": {
            "from": "now-6h",
            "to": "now"
          },
          "timepicker": {
            "refresh_intervals": [
              "5s",
              "10s",
              "30s",
              "1m",
              "5m",
              "15m",
              "30m",
              "1h",
              "2h",
              "1d"
            ]
          },
          "timezone": "",
          "title": "BeStrong API Logs",
          "uid": "bestrong-api",
          "version": 1
        }
