apiVersion: v1
kind: Service
metadata:
  name: {{ include "bestrongapp.serviceName" . }}
  labels:
    app: {{ include "bestrongapp.fullname" . }}
    tier: {{ .Values.labels.tier }}
spec:
  selector:
    app: {{ include "bestrongapp.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}
