replicaCount: 2

image:
  repository: bestrong
  tag: stable
  pullPolicy: Always

service:
  type: NodePort
  port: 80

containerPort: 80

ingress:
  host: bestrong.4.210.161.192.nip.io   # Fixed format: name.IP.nip.io
  canary:
    enabled: false                 # або true, якщо треба
    weight: 10

resources:
  limits:
    memory: "256Mi"
    cpu: "200m"
  requests:
    memory: "128Mi"
    cpu: "100m"

labels:
  app: webapp
  tier: backend

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  # Додаємо змінні для структурованого логування
  - name: ASPNETCORE_URLS
    value: "http://+:{{ .Values.containerPort }}"
  - name: Logging__LogLevel__Default
    value: "Information"
  - name: Logging__LogLevel__Microsoft
    value: "Warning"
  - name: Logging__LogLevel__System
    value: "Warning"
  # Налаштування для JSON логування (якщо підтримується вашим додатком)
  - name: Logging__Console__FormatterName
    value: "json"
  # Метадані для логів
  - name: APP_NAME
    value: "bestrong-api"
  - name: APP_VERSION
    value: stable
  - name: POD_NAME
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: POD_NAMESPACE
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName
